language: ruby
sudo: false
cache:
  directories:
    - workspace/redmine/vendor/bundle
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
  chrome: stable
rvm:
 - 3.0.0
 - 3.1.0
 - 3.2.0
 - 3.3.0
env:
  global: REDMINE_DIR=./workspace/redmine
  matrix:
   - REDMINE=6.0-stable
   - REDMINE=master
matrix:
  include:
   - rvm: 3.3.0
     env: REDMINE=master
gemfile: workspace/redmine/Gemfile
bundler_args: --path vendor/bundle --gemfile workspace/redmine/Gemfile --without development rmagick
before_install:
 - ./script/ci.sh clone_redmine --target $REDMINE_DIR
 - cp ./config/database.yml.travis $REDMINE_DIR/config/database.yml
 - ./script/ci.sh install_plugin_gemfile
before_script:
 - mysql -e 'CREATE DATABASE redmine CHARACTER SET utf8;'
 - ./script/ci.sh prepare_redmine
 - ./script/ci.sh prepare_plugin
 - ./script/ci.sh start_ldap
script:
 - ./script/ci.sh run_tests
 - ./script/ci.sh test_uninstall
